import { createFileRoute } from '@tanstack/react-router'
import { usePageTitle } from '@/hooks/use-page-title'
import { FieldWorksReviewConsole } from '@/screens/fieldworks/fieldworks-review-console'


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — routeTree.gen.ts is auto-generated by the Vite plugin. /fieldworks will be registered on next `pnpm dev` run.
export const Route = createFileRoute('/fieldworks' as any)({

  ssr: false,
  component: function FieldWorksRoute() {
    usePageTitle('FieldWorks Review Console')
    return <FieldWorksReviewConsole />
  },
  errorComponent: function FieldWorksError({ error }) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-6 text-center">
        <h2 className="text-xl font-semibold mb-3">FieldWorks Review Console Error</h2>
        <p className="text-sm opacity-60 mb-4 max-w-md">
          {error instanceof Error ? error.message : 'An unexpected error occurred'}
        </p>
        <button
          onClick={() => window.location.reload()}
          className="px-4 py-2 bg-accent-500 text-white rounded-lg hover:bg-accent-600 transition-colors"
        >
          Reload
        </button>
      </div>
    )
  },
  pendingComponent: function FieldWorksPending() {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-accent-500 border-r-transparent mb-3" />
          <p className="text-sm opacity-50">Loading FieldWorks Review Console...</p>
        </div>
      </div>
    )
  },
})
